# -*- coding: utf-8 -*-
"""projeto_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YBplW9BVxtRTkZTctqpz-8TzxY3SMAyM
"""

from sklearn.datasets import load_wine
wine = load_wine()
print(wine)